### PR TITLE
Replace querystring with qs

### PR DESCRIPTION
**Pull request by vramana**
Ref: https://github.com/defunctzombie/node-url/issues/57#issuecomment-1264684185

### CODE REVIEW

**Comment by vramana** [comment]
@ljharb It seems 0.6 version fails while compiling node itself if I understand correctly.

**Comment by ljharb** [comment]
yes, you don’t have to worry about that.

**Comment by vramana** [comment]
@ljharb Fixed conflicts and pushed changes again

**Comment by vramana** [comment]
@ljharb Ping

**Review by ljharb — APPROVED** [review]

**Pull request merged**
